// AUTO-GENERATED by scripts/build-schema-migrations.ts from src/core/schema-migrations/v<NNN>-*.ts.
// Do not edit or hand-merge. Regenerate: bun run build:schema-migrations
//
// The highest schema migration version (migrate.ts LATEST_VERSION), importable without
// loading the migrations themselves.

export const LATEST_SCHEMA_VERSION = 231;
