/**
 * The error code registry (agent operator contract v1, A2). Every literal
 * code thrown in `src/` has one entry here: its class (which derives the CLI
 * exit code and `retryable`), a one-sentence meaning, and optionally a
 * default suggestion, a default fix (diagnostic reads only), reasons, a docs
 * anchor and the frozen legacy wire value. `docs/guides/error-codes.md` is
 * generated from this table (`bun run build:error-codes`), and
 * `test/error-catalogue.test.ts` walks the source AST so an unregistered code
 * fails CI.
 *
 * Adding a code: add one entry (snake_case, no transport prefix), then run
 * `bun run build:error-codes`. Entries default their docs to
 * `docs/guides/error-codes.md#<code>`.
 */
import type { Action, Actor, Effect, ErrorClass } from './agent-output.ts';
import { FENCE_REASON_CODES } from './fence-repair/reasons.ts';

export interface CodeEntry {
  class: ErrorClass;
  /** What happened, one sentence. */
  summary: string;
  /** Why it happens / what it protects. */
  why?: string;
  /** Closed vocabulary for `reason` when one code covers several causes. */
  reasons?: readonly string[];
  /** Repo-relative anchor; default `docs/guides/error-codes.md#<code>`. */
  docs?: string;
  /** Default prose suggestion when a site supplies none. */
  suggestion?: string;
  /**
   * Default fix template: read-only diagnostics only (scanner-checked).
   * `{slug}`, `{source_id}`, `{request_id}`, `{operation}` placeholders are
   * filled from envelope/receipt fields at render time; an unfillable
   * template is dropped, never rendered with a placeholder.
   */
  fix?: Action;
  effects?: readonly Effect[];
  actor?: Actor;
  /** The code this one replaced (documented in error-codes.md "Legacy `error` values"). */
  renamed_from?: string;
  /** Frozen v1 `error` wire value some sites keep for this canonical code. */
  legacy_error?: string;
  /** CLI exit code; default derives from class (1). */
  exit?: number;
  retryable?: boolean;
}

export const CODES = {
  access_command_failed: { class: 'caller', summary: "Google connect credential error: access command failed.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  access_denied_test_user: { class: 'host_only', summary: "Google connect credential error: access denied test user.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  access_env_missing: { class: 'caller', summary: "Google connect credential error: access env missing.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  acknowledgment_unavailable: { class: 'unavailable', summary: "This batch is unknown or outside the retained replay window." },
  admin_policy_enforced: { class: 'host_only', summary: "Google connect credential error: admin policy enforced.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  ambient_capture_off: { class: 'caller', summary: "memory.auto_writeback no longer allows this ambient capture lane, so facts extracted from captured session text were dropped before admission.", why: "An explicit off (or an incoherent setting) applies to every capture-lane fact request admitted after the change, including one whose provider call was already in flight; requests admitted earlier still publish.", docs: 'docs/guides/ambient-writeback.md#capture-lanes-and-the-off-switch' },
  ambiguous_id: { class: 'caller', summary: "The legacy id matches multiple readable pages." },
  ambiguous_ref: { class: 'caller', summary: "A page reference in a rating matches pages in more than one source of that answer.", docs: 'docs/guides/retrieval-feedback.md#ambiguous_ref' },
  ambiguous_skill: { class: 'caller', summary: "This name belongs to multiple authorized sources." },
  answer_not_yours: { class: 'caller', summary: "The rated answer was returned to a different client.", docs: 'docs/guides/retrieval-feedback.md#answer_not_yours' },
  answer_pending: { class: 'retryable', summary: "The rated answer is still being recorded; retry in a few seconds.", docs: 'docs/guides/retrieval-feedback.md#answer_pending' },
  answer_unavailable: { class: 'caller', summary: "The rated answer is not recorded: unknown, dropped, or older than the retention window.", docs: 'docs/guides/retrieval-feedback.md#answer_unavailable' },
  api_not_enabled: { class: 'host_only', summary: "Google connect credential error: api not enabled.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  approval_required: { class: 'consent', summary: "The change needs the owner's explicit approval before it can proceed." },
  autopilot_job_owned_by_other_brain: { class: 'caller', summary: "The autopilot job is bound to a different brain." },
  budget_below_recent_runtime: { class: 'unavailable', summary: "The cycle's remaining budget fits fewer reflections than dream patterns needs at the recorded runtime, so the in-cycle run was skipped before any spend.", why: 'An in-cycle patterns run is sized from dream.patterns.last_run; a run that cannot finish in the budget would spend tokens and be killed.', docs: 'docs/guides/dream-patterns.md#budget-sizing', suggestion: 'Run `gbrain dream --phase patterns` outside the cycle after the user agrees to the paid run (it is not budget-limited and records its cost), or reset the record with `gbrain config unset dream.patterns.last_run`.' },
  benchmark_duplicate_task_id: { class: 'caller', summary: "Benchmark duplicate task id." },
  benchmark_empty: { class: 'caller', summary: "The benchmark file has no tasks." },
  benchmark_exists: { class: 'caller', summary: "A benchmark already exists at the target path." },
  benchmark_judge_llm_no_rubric: { class: 'caller', summary: "Benchmark judge llm no rubric." },
  benchmark_judge_qrels_no_expected: { class: 'caller', summary: "Benchmark judge qrels no expected." },
  benchmark_judge_rule_no_checks: { class: 'caller', summary: "Benchmark judge rule no checks." },
  benchmark_judge_unknown_kind: { class: 'caller', summary: "Benchmark judge unknown kind." },
  benchmark_malformed: { class: 'caller', summary: "A benchmark row is not valid JSON." },
  benchmark_missing_judge: { class: 'caller', summary: "Benchmark missing judge." },
  benchmark_missing_task: { class: 'caller', summary: "Benchmark missing task." },
  benchmark_missing_task_id: { class: 'caller', summary: "Benchmark missing task id." },
  benchmark_not_found: { class: 'caller', summary: "The benchmark file cannot be read." },
  benchmark_rule_check_bad_arg: { class: 'caller', summary: "Benchmark rule check bad arg." },
  benchmark_rule_check_malformed: { class: 'caller', summary: "Benchmark rule check malformed." },
  benchmark_rule_check_unknown_op: { class: 'caller', summary: "Benchmark rule check unknown op." },
  bootstrap_empty: { class: 'caller', summary: "The benchmark bootstrap produced no tasks." },
  bootstrap_pending_review: { class: 'caller', summary: "The bootstrapped benchmark awaits human review." },
  bridge_ownership_conflict: { class: 'caller', summary: "The private local CLI registration is invalid." },
  bucket_not_found: { class: 'unavailable', summary: "The configured storage bucket does not exist." },
  budget_unsatisfiable: { class: 'unavailable', summary: "Reserved by MEMORY_VERBS v1; never returned." },
  cache_quota_exceeded: { class: 'caller', summary: "Retained shared-skill revisions reached this installation's local cache quota.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  cancelled: { class: 'caller', summary: "The write was cancelled before it committed." },
  catalog_capacity_exceeded: { class: 'caller', summary: "The shared-skills catalog visible to this connection exceeds the delivery limits.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  catalog_unavailable: { class: 'retryable', summary: "Shared skill storage is not ready on this brain." },
  changed_since_preview: { class: 'caller', summary: "The file changed after its repair was previewed, so nothing was written.", why: "A repair writes exactly the bytes the operator approved; it binds approval to the previewed file hash and refuses when the file moved on.", suggestion: 'Preview the repair again, review the new proposal, and approve its new hash.' },
  chronicle_skipped: { class: 'unavailable', summary: "Automatic event extraction (auto_chronicle) skipped or failed this page; `reason` says why and `fix`, when present, is the next step.", reasons: ['auto_chronicle_off', 'auto_chronicle_invalid', 'slug_bound_client', 'operation_bound_client', 'no_extract', 'history', 'not_yet_happened', 'too_short', 'dream_generated', 'no_write_decision', 'not_chronicle_shaped', 'already_extracted', 'superseded', 'daily_limit', 'judge_llm_unavailable', 'no_pricing', 'budget_exhausted', 'campaign_exhausted', 'judge_chat_error', 'judge_truncated', 'judge_parse_failed', 'malformed_proposal', 'publish_error', 'judge_refused', 'page_missing', 'no_events', 'future_dated', 'date_imprecise', 'no_chat_provider'], docs: 'docs/guides/life-chronicle.md#skip-and-failure-codes', suggestion: 'Read the receipt or doctor `auto_chronicle` check: its `why` explains the reason and its `fix`, when present, is the next step (paid fixes need the user\'s agreement).' },
  checkpoint_missing: { class: 'caller', summary: "The approved source plan is missing; do not restart from a different revision." },
  checkpoint_validation_timeout: { class: 'retryable', summary: "Validating the managed-sync checkpoint timed out." },
  claim_already_used: { class: 'caller', summary: "Google connect credential error: claim already used.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  client_json_unreadable: { class: 'caller', summary: "Google connect credential error: client json unreadable.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  client_json_wrong_type: { class: 'caller', summary: "Google connect credential error: client json wrong type.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  client_shape_invalid: { class: 'caller', summary: "Google connect credential error: client shape invalid.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  code_callees_requires_symbol: { class: 'caller', summary: "code-callees requires a symbol name." },
  code_callers_requires_symbol: { class: 'caller', summary: "code-callers requires a symbol name." },
  code_def_requires_symbol: { class: 'caller', summary: "code-def requires a symbol name." },
  code_refs_requires_symbol: { class: 'caller', summary: "code-refs requires a symbol name." },
  code_reused: { class: 'caller', summary: "Google connect credential error: code reused.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  colon_slug_windows_write_through: { class: 'caller', summary: "A colon slug cannot be written through on Windows." },
  command_failed: { class: 'server', summary: "The command failed before it wrote its JSON result." },
  concurrent_write: { class: 'caller', summary: "A managed sync import raced a database-only write to the same page, so the file is held and the page keeps the database version; neither was overwritten.", why: "The page's live revision was written by a committed non-sync request after the import was frozen, so the Git file and the database genuinely diverge; choosing either silently would lose the other.", docs: 'docs/guides/write-refusals.md#concurrent_write', suggestion: 'Preview the reconciliation with gbrain sources reconcile <source> <slug> --preview, resolve it with the user, then run gbrain sources retry-held <source> and gbrain sync --source <source> --no-pull.' },
  config_error: { class: 'caller', summary: "A required configuration value or directory is missing or invalid." },
  confirmation_required: { class: 'consent', summary: "The command needs the user's authorization before it runs; nothing was changed.", exit: 3 },
  conflicting_source_scope: { class: 'caller', summary: "--source and --all-sources were both given." },
  connection_lost: { class: 'retryable', retryable: true, actor: 'agent',
    summary: "The managed sync drain lost its database connection three times in a row without committing a page in between, so it stopped where the cursor stands; nothing is recorded against the source.",
    why: "A pooler drop (ECONNABORTED, ECONNRESET, ETIMEDOUT, EPIPE) is a transport fault, not a page fault: the drain reconnects and retries at 5, 15 and 45 seconds, and the frozen manifest and cursor stay as they are. Three consecutive drops with no progress mean the database is unreachable from here for now.",
    docs: 'docs/guides/write-refusals.md#drain-connection-lost',
    suggestion: 'Check the database URL and pooler (gbrain doctor --json), then rerun the same gbrain sync; it resumes at the stored cursor without re-freezing the manifest.' },
  connector_account_changed: { class: 'caller', summary: "The connector credential resolves to a different account than the source is pinned to." },
  connector_fence_below_timeline: { class: 'caller', summary: "A stored page carries a fence the connector render cannot preserve." },
  connector_holds_exhausted: { class: 'caller', summary: "The source holds the maximum number of failed items; its cursor did not advance." },
  connector_intent_outdated: { class: 'caller', summary: "The connector request no longer matches the stored connector intent." },
  consent_timeout: { class: 'consent', summary: "Google connect credential error: consent timeout.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  consumers_without_heartbeat: { class: 'host_only', summary: "Running write claims on this host are stamped by a process that writes no `persistence_consumers` heartbeat row, so its liveness and mode cannot be read.", why: "Every full consumer on this release renews a heartbeat row every 10 s; a claim owner with no row is a gbrain process from before the heartbeat table (an older `serve`, jobs worker or sync CLI), which also never defers to the resident consumer, so the host may run two full consumers until it is upgraded.", docs: 'docs/guides/troubleshooting.md#consumers-without-heartbeat', suggestion: 'Upgrade and restart the process whose pid the check names (its kind and gbrain version come from the claim stamp); until then the host runs its consumer beside the resident one.', fix: { argv: ['gbrain', 'sources', 'writer', 'status', '--json'], consent: [], actor: 'agent', why: 'Read-only: lists the consumers alive on this host with their heartbeat rows beside the running claims and the owner each claim stamps.', requires_exclusive: false, verify: { argv: ['gbrain', 'doctor', '--only', 'consumers_without_heartbeat', '--json'] } } },
  content_repair_needs_human: { class: 'caller', retryable: false, actor: 'user',
    summary: "The content-repair model could not decide whether a held file and the page its frontmatter `slug:` names are the same page, so nothing was written and a person decides which keeps the slug.",
    why: "A `frontmatter_slug_conflict` hold that the deterministic rules cannot clear (the named page exists and shares a type or a title word with the file) goes to the judgment model; `needs_human` is its answer when the shown frontmatter, headings, opening lines and cross-mentions do not decide identity. Removing the `slug:` line on a guess would mint a second page for the same thing, and merging on a guess would fold two different things together, so gbrain records the verdict on the hold as codes and slugs, retries nothing until the file changes, and the rest of the source keeps syncing.",
    docs: 'docs/guides/write-refusals.md#content_repair_needs_human',
    suggestion: 'Show the user the paragraph gbrain sources status <id> --json renders for the hold (the path and the two slugs). If the two differ, remove the slug: line of the file; if they are one page, merge the unique sections into the page that keeps the slug and delete the other file; then commit and run gbrain sync --source <id> --no-pull.',
    fix: { argv: ['gbrain', 'sources', 'status', '{source_id}', '--json'], consent: [], actor: 'user', requires_exclusive: false,
      why: 'Read-only: lists the held file with the two slugs and the rendered paragraph; the user decides which page keeps the slug before anything is edited.',
      verify: { argv: ['gbrain', 'sources', 'status', '{source_id}', '--json'] } } },
  content_rejected: { class: 'caller', summary: "The content-sanity gate rejected the content because the operator set `content_sanity.junk_disposition` to `reject`.", why: "A junk-pattern or operator-literal hit is refused instead of quarantined under that setting, so the page was not written. The same content refuses on every retry.", suggestion: 'Remove the matched junk from the file, or switch `content_sanity.junk_disposition` back to `quarantine` (a user decision), then import it again.' },
  core_budget_exceeded: { class: 'caller', summary: "The write would push always-loaded core memory over its brain-wide character budget or page limit.", why: "Core pages enter every session's prompt in every harness, so their total size is capped on the write path.", docs: 'docs/guides/core-memory.md#budget', fix: { argv: ['gbrain', 'core', 'status', '--json'], consent: [], actor: 'agent', why: "Shows core usage against the budget and the largest core pages, read-only.", requires_exclusive: false } },
  core_delete_owner_only: { class: 'consent', summary: "A remote caller tried to delete an always-loaded core page; only the owner can remove pages from core.", docs: 'docs/guides/core-memory.md#owner-only', actor: 'user' },
  core_mark_owner_only: { class: 'consent', summary: "A remote caller tried to change always_load or core_priority; only the owner designates core pages.", docs: 'docs/guides/core-memory.md#owner-only', actor: 'user' },
  core_remote_edit_refused: { class: 'consent', summary: "Remote edits to always-loaded core pages are refused by memory.core.remote_edit.", docs: 'docs/guides/core-memory.md#remote-edits', actor: 'user' },
  cost_cap_exceeded: { class: 'server', summary: "The run reached its cost cap before finishing." },
  cost_preview_requires_yes: { class: 'consent', summary: "Cost preview requires yes." },
  cycle_failed: { class: 'server', summary: "The maintenance (dream) cycle failed, or a phase threw and was contained so later phases could run." },
  d_sel_too_small: { class: 'caller', summary: "The selection split has too few tasks for meaningful validation." },
  database_error: { class: 'server', summary: "The brain database could not be reached or refused the operation." },
  delta_cursor_upgrade_required: {
    class: 'caller',
    summary: "A since/since_slug delta call reached more undelivered facts at one timestamp than that cursor can page; repeat the call with the opaque cursor.",
    why: "The legacy cursor is a single timestamp, so facts that share one can only be paged by fact id, which next_cursor.cursor carries. Nothing was skipped and no cursor moved.",
    suggestion: "Repeat the delta call with the cursor from fix (next_cursor.cursor) instead of since/since_slug, and keep passing next_cursor.cursor afterwards.",
    docs: 'docs/guides/ambient-recall.md#replay-after-a-degraded-wake',
  },
  demo_graph_failed: { class: 'server', summary: "The fictional graph did not verify." },
  demo_import_failed: { class: 'server', summary: "The fictional page did not import successfully." },
  demo_verification_failed: { class: 'server', summary: "Expected ownership or decision provenance is missing." },
  derived_cap_exhausted: { class: 'server', summary: "Paid work stopped at the cost cap derived from its estimate; the run is resumable." },
  destination_not_ready: { class: 'host_only', summary: "The destination brain is not initialized for this operation." },
  drain_stalled: { class: 'server', retryable: false, actor: 'host_admin',
    summary: "A managed sync drain stopped `blocked` because its head write made no progress (no committed receipt and no step advance) for the whole stall window.",
    why: "A renewed lease is not progress: the detector keys on the head claim's phase and step. With a live owner on this host the drain prints `stalled <N>s on <step>` from the allowance (budget plus 30 s) and keeps going; it stops only when `persistence.preparation_ceiling_ms` passes without the root being released, or when that owner's heartbeat row reads wedged (`cause: owner_wedged_here`, with the owner's kind, pid and nonce and `retry_after_ms` to the ceiling, after which the owner frees the root and the next pass holds the entry). A lapsed claim (`owner_missing`) stops at once unless this host owns the checkout and a live full consumer can reclaim it, which gets one more window. `drain.stall.cause` names which.",
    reasons: ['owner_wedged_here', 'owner_missing', 'preparation_overdue', 'publication_overdue', 'no_progress'],
    docs: 'docs/guides/write-refusals.md#drain-stalled',
    suggestion: 'Inspect the writer with gbrain sources writer status --source <id> --json (read-only: the owner process, its step and what it waits on, and the next action). Before the ceiling (`next.safe_to_loop` true) rerun next.command after retry_after_ms; past it, or with a wedged owner, restart the named owner process on the brain host and rerun the same sync.',
    fix: { argv: ['gbrain', 'sources', 'writer', 'status', '--source', '{source_id}', '--json'], consent: [], actor: 'agent', why: "Read-only: names the owner process holding the head write (kind, pid), its step and wait cause, and ends in a next_action.", requires_exclusive: false,
      verify: { argv: ['gbrain', 'doctor', '--only', 'managed_sync_not_moving', '--json'] } } },
  dream_breaker_tripped: { class: 'unavailable', summary: "A dream synthesize or patterns submission died (or, for patterns, was cancelled at its timeout after paid work) the breaker limit of times within 24 hours, so it was not submitted again.", why: "A run that keeps dying keeps paying; the breaker stops resubmitting until the cause is fixed and the key is reset. Patterns count per source (`dream:patterns:source:<id>`) whatever reflections each run read, and a completed run resets that count.", docs: 'docs/operations/spend-controls.md#dream-paid-loop-breaker-dreambreakermax_dead_submissions', fix: { argv: ['gbrain', 'doctor', '--only', 'dream_paid_loop', '--json'], consent: [], actor: 'agent', why: 'Shows the tripped dream keys with their counts and reset commands, read-only.', requires_exclusive: false } },
  dirty_tree: { class: 'caller', summary: "Commit or stash canonical skill edits before optimization." },
  effect_not_failed: { class: 'caller', summary: "Only a failed, non-running embedding effect can be explicitly retried." },
  embedding_auth_failed: { class: 'unavailable', summary: "The embedding provider rejected the credentials." },
  embedding_budget_below_worst_case: { class: 'unavailable', summary: "The embedding migration cap is below its worst-case cost; nothing was changed." },
  embedding_configuration: { class: 'host_only', summary: "The brain's embedding configuration is invalid." },
  embedding_disabled: { class: 'unavailable', summary: "Embeddings are disabled on this brain." },
  embedding_failed: { class: 'server', summary: "Computing embeddings for the content failed." },
  embedding_model_mismatch: { class: 'unavailable', summary: "The configured provider does not match the active embedding column." },
  embedding_plane_split: { class: 'unavailable', summary: "Embedding plane split." },
  embedding_storage_unavailable: { class: 'retryable', summary: "Embedding policy or claim storage is temporarily unavailable." },
  embedding_unavailable: { class: 'unavailable', summary: "The provider returned an incomplete embedding batch." },
  embedding_unconfigured: { class: 'host_only', summary: "The selected brain has no verifiable text embedding model and dimensions." },
  embedding_width_mismatch: { class: 'caller', summary: "The embedding model cannot produce the width of the brain's vector column; nothing was changed." },
  engine_graduated: { class: 'caller', summary: "A client opened a PGLite brain that moved to Postgres; its old path holds a tombstone.", docs: 'docs/guides/move-to-postgres.md#graduated-datastore' },
  eval_suite_unwired: { class: 'caller', summary: "`gbrain eval run-all` was asked for a suite it does not run in-process (longmemeval or replay); nothing ran.", why: "run-all runs only wired suites (brainbench). Recording a skipped run and exiting 0 would read as a completed sweep with no numbers behind it.", suggestion: 'Run each requested suite with its own command (`gbrain eval longmemeval <dataset.jsonl> --mode <mode> --record`, `gbrain eval replay --mode <mode>`), once per mode, or drop it from --suites.' },
  export_limit: { class: 'caller', summary: "This migration is bounded to 5,000 active pages per source; split or use a reviewed bulk export." },
  extraction_failed: { class: 'server', summary: "The accepted atom extraction failed (malformed output, or a response stopped before the end); a new attempt needs approval.", why: "A failed managed atom batch is recorded as a failure receipt instead of being retried automatically, so the same input is not paid for every cycle." },
  extractor_identity_mismatch: { class: 'server', summary: "The approved extractor differs from the installed extractor; this receipt cannot resume or admit another revision." },
  fact_already_expired: { class: 'caller', summary: "The fact had already expired before this write." },
  fence_unrenderable: { class: 'server', summary: "A legacy fact row was not adopted into its page's facts fence because the fence codec reads the rendered row back as something other than the stored fact.", why: "The fence trims a claim, folds CRLF to LF, reads `~~x~~` as a struck row and `<br>` as a line break; a claim the codec would change by more than whitespace cannot be written into the fence without changing what it says, so the row stays a legacy row (active and searchable, nothing is lost) and is counted by doctor fence_integrity as unrenderable_legacy_facts. The same code names a planned adoption whose rendered fence does not read back as its facts; that is a gbrain planning defect, not caller input.", docs: 'docs/guides/write-refusals.md#fence_unrenderable', suggestion: 'Nothing to fix in the page: the rows stay active and searchable. Report the page slug and the reason class with the gbrain version; do not forget or expire a row to clear this count.', fix: { argv: ['gbrain', 'doctor', '--only', 'fence_integrity', '--json'], consent: [], actor: 'agent', why: 'Lists the pages whose legacy fact rows cannot be adopted into their fence and why (by fact id and reason class, never the claim text), read-only.', requires_exclusive: false } },
  fact_not_found: { class: 'caller', summary: "Fact not found." },
  facts_absorb_write_refused: { class: 'caller', summary: "Facts absorb refused the write." },
  facts_backstop_skipped: { class: 'unavailable', summary: "A page write queued no automatic fact extraction; the receipt's `facts_backstop.skipped` reason says why (a `kind:<type>` reason names a page type that is not extracted).", reasons: ['opted_out', 'quarantined', 'body_unchanged', 'extraction_disabled', 'dream_generated', 'subagent_namespace', 'too_short', 'no_parsed_page', 'slug_bound_client', 'operation_bound_client', 'not_imported', 'backstop_error'], docs: 'docs/guides/concurrent-writes.md#facts-backstop', suggestion: 'Nothing failed. `opted_out` means the page frontmatter sets `facts_backstop: false`; remove that line and save the page to extract it.', fix: { argv: ['gbrain', 'get', '--source', '{source_id}', '--', '{slug}'], consent: [], actor: 'agent', why: 'Shows the page frontmatter that decided the skip.', requires_exclusive: false } },
  facts_drain_deferred: { class: 'unavailable', summary: "The automatic facts drain left queued facts-absorb jobs waiting; `reason` says why and `fix`, when present, is the next step. Nothing is dropped: the jobs run on a later drain.", reasons: ['no_key', 'extraction_unavailable', 'budget_exhausted', 'daily_budget_exhausted', 'job_over_budget', 'no_pricing', 'provider_halted', 'drain_error'], docs: 'docs/guides/facts-drain.md#deferrals', suggestion: 'Read doctor `facts_drain`: its message names the cause and its fix the next step (raising a spend cap is paid; ask the user first).', fix: { argv: ['gbrain', 'doctor', '--only', 'facts_drain', '--json'], consent: [], actor: 'agent', why: 'Shows the drain status, the backlog and the last error with its fix.', requires_exclusive: false } },
  facts_drain_job_failed: { class: 'server', summary: "A facts-absorb job failed inside the automatic facts drain; it retries with backoff until its attempts run out.", docs: 'docs/guides/facts-drain.md#deferrals', suggestion: 'Read doctor `facts_drain`: its message names the cause and its fix the next step (raising a spend cap is paid; ask the user first).', fix: { argv: ['gbrain', 'doctor', '--only', 'facts_drain', '--json'], consent: [], actor: 'agent', why: 'Shows the drain status, the backlog and the last error with its fix.', requires_exclusive: false } },
  facts_payload_expired: { class: 'server', summary: "The accepted fact extraction failed and its retained payload has expired." },
  feedback_disabled: { class: 'host_only', summary: "Retrieval feedback is off (or not learning) on this brain, so ratings are not recorded.", docs: 'docs/guides/retrieval-feedback.md#feedback_disabled' },
  feedback_not_authorized: { class: 'host_only', summary: "This caller may not change the brain's shared ranking for that source.", docs: 'docs/guides/retrieval-feedback.md#feedback_not_authorized' },
  fetch_failed: { class: 'retryable', summary: "Fetching the upstream failed." },
  fix_not_writable: { class: 'host_only', summary: "A gbrain lint fix was not applied because the file refused the write (EACCES, EPERM or EROFS); the file was left unchanged.", why: "Lint repairs files in place, and this file's permissions or a read-only mount stopped the write; lint reports it and continues with the remaining files.", docs: 'docs/guides/repair.md#fix-not-writable', suggestion: "Make the file writable by the user running gbrain, or pass its directory or file name to gbrain lint --exclude, then lint again." },
  file_removed_during_scan: { class: 'retryable', summary: "A file lint listed was removed before lint read it, so it was not linted.", why: "Another process deleted or renamed the file during the run; lint reports it and continues with the remaining files.", docs: 'docs/guides/repair.md#file-removed-during-scan', suggestion: "Re-run gbrain lint on the same target; it lints the files present now." },
  file_too_large: { class: 'caller', summary: "The file is over the import size limit (5 MB for Markdown and code, 10 MiB for any sync read), so it was not imported.", why: "Size limits bound parsing, chunking and embedding cost. The same bytes refuse on every retry.", suggestion: 'Split the file into smaller files, or leave it out of the source (sync.exclude), then sync or import again.' },
  follow_approval_required: { class: 'caller', summary: "Following a brain's shared skills needs the user's explicit follow approval.", docs: 'docs/guides/shared-brain-skills.md#approve-publication-following-and-editing-separately' },
  forget_requires_owner: { class: 'consent', exit: 3, actor: 'user', summary: "A remote caller asked to forget a fact more trusted than its own writes, so nothing was forgotten and the owner was asked instead.", why: "Lower-trust writers cannot overwrite, supersede or forget what the owner confirmed or curated (#5575 guarded supersession). The request became a trust proposal the owner can accept on the brain host; forget's frozen expired meaning is unchanged because nothing expired.", docs: 'docs/guides/error-codes.md#forget_requires_owner', suggestion: 'Do not retry. Tell the user the fact needs their decision and give them the command in fix (gbrain trust confirm <proposal_ref> on the brain host).' },
  frontmatter_slug_conflict: { class: 'caller', summary: "The file's frontmatter `slug:` names a different page than its path does.", why: "The path decides a file's page; a conflicting declared slug would overwrite or fork another page, so the file is refused until one of them changes.", suggestion: 'Remove the `slug:` line or make it match the path, then commit and sync again.' },
  full_resync_required: { class: 'retryable', summary: "The catalog cursor is invalid or expired." },
  gate_failed: { class: 'caller', summary: "The eval gate found retrieval regressions or correctness below its thresholds." },
  git_index_locked: { class: 'retryable', summary: "Another Git process holds the canonical checkout index lock." },
  git_index_stale: { class: 'caller', summary: "Git index stale." },
  git_push_unavailable: { class: 'retryable', summary: "The canonical commit is durable locally; its push will retry." },
  git_target_unsafe: { class: 'caller', summary: "Git cannot identify the existing canonical file by its native spelling." },
  git_unavailable: { class: 'retryable', summary: "A git command did not complete." },
  graduation_drain_timeout: { class: 'retryable', summary: "Queued or running writes did not drain within --drain-timeout; the move stopped before copying and the source is unchanged.", docs: 'docs/guides/move-to-postgres.md#drain', reasons: ['progressing', 'blocked'], exit: 11 },
  graduation_embedding_dimension_mismatch: { class: 'caller', summary: "An existing, non-empty target database has a different embedding column layout than the brain being moved.", docs: 'docs/guides/move-to-postgres.md#embeddings' },
  graduation_foreign_host_binding: { class: 'host_only', summary: "A source's worktree is owned by another host, so this host cannot move it to Postgres.", docs: 'docs/guides/move-to-postgres.md#hosts' },
  graduation_in_progress: { class: 'retryable', summary: "Another process is moving this brain to Postgres; neither engine may be opened until it finishes.", docs: 'docs/guides/move-to-postgres.md#in-progress', exit: 75 },
  graduation_interrupted: { class: 'unavailable', summary: "An engine graduation stopped before it finished and no process owns it.", docs: 'docs/guides/move-to-postgres.md#resume' },
  graduation_rollback_writes_lost: { class: 'consent', summary: "Rolling back to PGLite would drop changes made on Postgres since the move.", docs: 'docs/guides/move-to-postgres.md#rollback', reasons: ['user_data', 'security_changes'] },
  graduation_source_writer_held: { class: 'host_only', summary: "A live serve or daemon holds the PGLite brain and did not hand it over to the move.", docs: 'docs/ENGINES.md#graduation-writer-held' },
  graduation_split_brain: { class: 'unavailable', summary: "A different brain appeared at the graduated brain's old path; the target is withheld from authority until the user decides.", docs: 'docs/guides/move-to-postgres.md#split-brain' },
  graduation_target_auth_failed: { class: 'caller', summary: "The target database rejected the credentials recorded for this move.", docs: 'docs/guides/move-to-postgres.md#credentials' },
  graduation_target_ddl_unreachable: { class: 'unavailable', summary: "The target's direct (schema) connection is unreachable or names a different database than its main URL.", docs: 'docs/guides/move-to-postgres.md#ddl-connection' },
  graduation_target_not_empty: { class: 'caller', summary: "The target database already holds data that is not this move's.", docs: 'docs/guides/move-to-postgres.md#target-not-empty' },
  graduation_target_unsupported: { class: 'caller', summary: "The target database is missing a prerequisite (server version, vector extension with halfvec, CREATE privilege or a matching column).", docs: 'docs/guides/move-to-postgres.md#target-requirements', reasons: ['server_version', 'vector', 'halfvec', 'create_privilege', 'column', 'env_override'] },
  graduation_unclassified_table: { class: 'server', summary: "A database has a relation the graduation inventory does not classify, so moving it could lose data.", docs: 'docs/guides/move-to-postgres.md#inventory', reasons: ['newer_schema', 'missing_inventory_row'] },
  graduation_unsupported_platform: { class: 'host_only', summary: "Moving a brain with write history to Postgres is not available on this platform yet.", docs: 'docs/guides/move-to-postgres.md#platforms' },
  graduation_verify_failed: { class: 'server', summary: "The moved copy did not verify against the source; the target stays fenced and the source stays authoritative.", docs: 'docs/guides/move-to-postgres.md#verify', reasons: ['count', 'digest', 'sequence', 'fk', 'trigger', 'relation_set', 'replay', 'doctor'] },
  graph_incomplete: { class: 'server', summary: "Source relationship reconciliation is incomplete." },
  host_identity_mismatch: { class: 'host_only', summary: "This process's `host.json` identity differs from the identity that owns the binding although both resolve on this machine, so writes that need the owner read it as another host.", why: "Host identity is a file under the persistence home: a job worker or container launched with a different `HOME` or `GBRAIN_HOME` mints a new `host.json` and sees the binding as another host's (`owner_unavailable`, `host_mismatch`), so its maintenance writes never reach the owner. The check names both files and the environment each was minted under (`minted_under`, `unknown` for a file minted before it was recorded); re-deriving the identity would re-own every existing binding, so the fix is the environment, never the file.", docs: 'docs/guides/troubleshooting.md#host-identity-mismatch', suggestion: 'Set GBRAIN_HOME on the supervisor of the process to the owner\'s home (the value the check prints; config appends .gbrain itself) and restart it; never edit or delete a host.json.', fix: { argv: ['gbrain', 'doctor', '--only', 'host_identity_mismatch', '--json'], consent: [], actor: 'host_admin', why: 'Read-only: names both host.json paths, the HOME and GBRAIN_HOME each was minted under and the GBRAIN_HOME value to set.', requires_exclusive: false, verify: { argv: ['gbrain', 'doctor', '--only', 'host_identity_mismatch', '--json'] } } },
  harness_hook_duplicates: { class: 'caller', summary: "A harness hook carrier wires one Claude Code event more than once with this install's own entries (marked or not), so the hook fires twice per event.", why: "Claude Code can drop the `_gbrain` marker when it rewrites settings.json; installs before wave 11 then appended a second set on every re-run.", docs: 'docs/guides/bootstrap.md#harness_hook_duplicates', fix: { argv: ['gbrain', 'doctor', '--only', 'bootstrap_harness_health', '--json'], consent: [], actor: 'agent', why: "Names the carrier, the duplicated events and the re-run (with the install's own flags) that converges them, read-only.", requires_exclusive: false } },
  harness_hook_unowned: { class: 'caller', summary: "A hook entry looks like gbrain's harness hook but is not this install's exact command, so gbrain left it in place.", why: "An unmarked entry is deleted only when its command is exactly what this install (or its receipt) wrote; an edited command or another install's launcher is never removed, and removal is not reported complete while it remains.", docs: 'docs/guides/bootstrap.md#harness_hook_unowned', fix: { argv: ['gbrain', 'bootstrap', 'harness', '--status'], consent: [], actor: 'agent', why: 'Shows each hook carrier with the events holding entries that are not this install\'s, read-only.', requires_exclusive: false } },
  held_out_overlaps_benchmark: { class: 'caller', summary: "Held out overlaps benchmark." },
  held_out_required_for_bundled: { class: 'caller', summary: "Held out required for bundled." },
  idempotency_conflict: { class: 'caller', summary: "The request_id already belongs to a different accepted operation." },
  independent_principal_required: { class: 'consent', summary: "This local CLI principal already owns another source/destination for this harness." },
  insufficient_scope: { class: 'host_only', summary: "The connection lacks the OAuth scope the operation requires.", legacy_error: 'permission_denied' },
  internal: { class: 'server', summary: "A memory verb failed on the server; this is not a caller mistake." },
  internal_error: { class: 'server', summary: "The server failed while running the operation; this is not a caller mistake." },
  interrupted: { class: 'server', summary: "The operation was interrupted by a signal before it finished.", exit: 130 },
  invalid_acknowledgment: { class: 'caller', summary: "The shared-skills delivery acknowledgment does not match a batch issued to this enrollment.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  invalid_client: { class: 'caller', summary: "Google connect credential error: invalid client.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  invalid_connector_text: { class: 'caller', summary: "Invalid connector text." },
  invalid_fence: { class: 'caller', summary: "A facts or takes fence in the page cannot be imported without dropping or guessing rows, so the page (or the file) was not written.", why: "Facts and takes fences are the page's structured rows. Importing a fence that does not parse, repeats a marker or reuses a row number would silently drop or renumber rows, so coordinated writers refuse it and managed sync holds the one file while the rest of the source syncs.", reasons: FENCE_REASON_CODES, legacy_error: 'invalid_params', docs: 'docs/guides/write-refusals.md#invalid_fence', suggestion: 'A refused write: fix the fence the message names (fence, section and rows; the reason says what is wrong) and send the page again with a new request_id, or write rows with remember / takes_add. A held file or stored page: the maintenance run repairs it; preview it now with gbrain repair fences --source <id> on the brain host.' },
  invalid_frontmatter: { class: 'caller', summary: "The file's YAML frontmatter cannot be read without guessing, so it was not imported.", why: "gbrain imports frontmatter it can read exactly (quoting an unquoted value at most). Guessing could store a wrong title, merge a duplicate, or read a protected key such as `visibility` as a broader value.", reasons: ['yaml_parse', 'needs_interpretation', 'ambiguous_identity_key', 'ambiguous_protected_key'], suggestion: 'Fix the named line in the file (one line per key, the whole value quoted), then commit and sync or import again.' },
  invalid_grant_clock_skew: { class: 'caller', summary: "Google connect credential error: invalid grant clock skew.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  invalid_grant_revoked: { class: 'caller', summary: "Google connect credential error: invalid grant revoked.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  invalid_grant_testing_expiry: { class: 'caller', summary: "Google connect credential error: invalid grant testing expiry.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  invalid_params: { class: 'caller', summary: "A parameter is missing, has the wrong type, or has an invalid value.", exit: 2 },
  invalid_rating: { class: 'caller', summary: "A rating must be an integer from 1 to 5.", docs: 'docs/guides/retrieval-feedback.md#invalid_rating' },
  invalid_receipt: { class: 'server', summary: "A company-source ingestion receipt input failed validation inside gbrain; nothing was written.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  invalid_receipt_transition: { class: 'caller', summary: "An ingestion receipt cannot skip a phase or complete while files failed, writes are pending or verification failed.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  invalid_request: { class: 'caller', summary: "submit_agent over the local CLI: use `gbrain agent run` instead." },
  invalid_source: { class: 'caller', summary: "The source argument or source state is invalid for this operation." },
  invalid_source_pin: { class: 'caller', summary: "The .gbrain-source pin names an invalid source id." },
  invalid_source_uri: { class: 'caller', summary: "The page has a stored file source_uri that cannot be resolved to a local filesystem path." },
  invalid_token: { class: 'host_only', summary: "The bearer token is missing, invalid, or revoked." },
  invalid_write_wait: { class: 'caller', summary: "Invalid write wait." },
  legacy_job_selection_invalid: { class: 'caller', summary: "The legacy job selection is invalid." },
  legacy_jobs_active: { class: 'caller', summary: "Legacy jobs are still active." },
  local_conflict: { class: 'caller', summary: "A local file or registration conflicts with the requested change." },
  lock_busy: { class: 'retryable', summary: "Another process holds the lock this command needs." },
  maintenance_backpressure: { class: 'retryable', summary: "Managed maintenance stopped admitting requests because this writer's outstanding requests, reserved receipt bytes or permanent request ids would pass 80% of their limit; nothing more was submitted.", why: "Each page of a maintenance run publishes as its own request under the local CLI writer the user's own CLI writes share. Stopping at 80% leaves room for those writes: reserved receipt bytes free only when receipts compact, request ids never.", docs: 'docs/guides/write-refusals.md#maintenance_backpressure', fix: { argv: ['gbrain', 'sources', 'writer', 'status', '--source', '{source_id}', '--json'], consent: [], actor: 'agent', why: "Shows the pending requests holding this writer's capacity, read-only.", requires_exclusive: false }, exit: 12 },
  maintenance_lock_busy: { class: 'retryable', summary: "A source-scoped dream cycle skipped its brain-wide phases because another cycle (usually autopilot maintenance) holds the shared gbrain-cycle lease; its source phases still ran.", why: 'Brain-wide phases (synthesize, patterns, embed, purge and the other mixed or global phases) must not run twice at once, so a cycle that cannot take gbrain-cycle runs only the phases its own source lease covers.', docs: 'docs/guides/cron-schedule.md#dream-beside-autopilot', suggestion: 'Nothing is lost: the holder runs those phases itself. To run one now, wait until the lease is released, then re-run `gbrain dream --phase <phase>` (LLM-backed phases spend; ask the user first).', fix: { argv: ['gbrain', 'status', '--section', 'locks', '--json'], consent: [], actor: 'agent', why: 'Shows who holds gbrain-cycle and when its lease expires, read-only.', requires_exclusive: false } },
  merge_recommended: { class: 'caller', retryable: false, actor: 'user',
    summary: "The content-repair model judged a held file and the page its frontmatter `slug:` names to be the same page, so gbrain recommends merging them instead of removing the slug line; nothing was written.",
    why: "A `frontmatter_slug_conflict` hold whose two sides describe the same person, company or topic is a duplicate, and the deterministic repair (delete the `slug:` line) would mint a second page for it. gbrain does not merge pages by itself yet (a lossless merge needs a coordinated two-page write with both revisions, withdrawal and metadata preservation; it ships separately), so the lane records the recommendation on the hold as codes and slugs (`meta.content_repair`: the canonical slug that keeps the page), `gbrain sync status` renders a paragraph for a person, and nothing retries it until the file changes.",
    docs: 'docs/guides/write-refusals.md#merge_recommended',
    suggestion: 'Show the user the paragraph gbrain sources status <id> --json renders for the hold (the path, the canonical slug and the recommendation). After they agree, merge the unique sections of the duplicate into the canonical page, delete the duplicate file, commit, and run gbrain sync --source <id> --no-pull; the hold clears on that sync.',
    fix: { argv: ['gbrain', 'sources', 'status', '{source_id}', '--json'], consent: [], actor: 'user', requires_exclusive: false,
      why: 'Read-only: lists the held file with the canonical slug gbrain recommends and the rendered paragraph; merging two pages is the user\'s decision.',
      verify: { argv: ['gbrain', 'sources', 'status', '{source_id}', '--json'] } } },
  managed_sync_not_moving: { class: 'server', retryable: false, actor: 'host_admin',
    summary: "A managed source has unfinished sync work and a live consumer on its owner host, but no committed `managed_sync_*` receipt and no head step advance for longer than `persistence.preparation_ceiling_ms`.",
    why: "Process liveness is not data movement: `/health` ok, a live pid and `sync_running: true` all held while one deployment moved nothing for weeks. `sources status --json` carries `data_moving`, `not_moving_since` and `movement_state` per source (`parked` when no drain or full consumer is live, informational), doctor warns with this code and counts it against the score, `serve` prints one notice when a source flips, and `gbrain sources writer movement` judges a window after a restart and exits 1 with this code (`reason: movement_check`) when pending work does not move.",
    reasons: ['movement_check'],
    docs: 'docs/guides/troubleshooting.md#managed-sync-not-moving',
    suggestion: 'Run gbrain sources writer status --source <id> --json (read-only): its next_action names the owner process, the step it is parked on and whether to wait or restart it. After the fix, gbrain sources writer movement proves the data moves again.',
    fix: { argv: ['gbrain', 'sources', 'writer', 'status', '--source', '{source_id}', '--json'], consent: [], actor: 'agent', why: 'Read-only: the owner process, the head write\'s step and wait cause, and a next_action (wait with retry_after_ms, or restart the named pid).', requires_exclusive: false, verify: { argv: ['gbrain', 'doctor', '--only', 'managed_sync_not_moving', '--json'] } } },
  managed_pull_skipped: { class: 'retryable', summary: "The managed pull was skipped." },
  manual_only_skipped: { class: 'consent', summary: "An automatic remediation run (`gbrain onboard --auto`, `doctor --remediate`, MCP `run_onboard`, autopilot) did not submit a manual-only step: the schema-pack upgrade (`unify-types`) or the paid takes bootstrap (`extract-takes-from-pages`).", why: "A pack upgrade retypes pages and switches the brain's schema pack, and the takes bootstrap pays a model per page; both are the user's one-time decision, so only the user submits them. A job of that kind an earlier run already queued is listed in `queued_jobs` and still runs unless cancelled.", actor: 'user', suggestion: 'Show the user the step and its `fix.command` (`gbrain jobs submit <job> --follow`, with `--params` when the step has them); the user runs it after reviewing `gbrain onboard --check`. Cancel a listed queued job with `gbrain jobs cancel <id>` if the user does not want it.', fix: { argv: ['gbrain', 'jobs', 'list', '--status', 'waiting'], consent: [], actor: 'agent', requires_exclusive: false, why: 'Lists queued jobs, including any manual-only job an earlier run queued.' } },
  membership_inactive: { class: 'caller', summary: "The shared-skills enrollment epoch was left or superseded.", docs: 'docs/guides/shared-brain-skills.md#membership-inactive-after-a-re-enrollment' },
  membership_not_found: { class: 'caller', summary: "This principal has no shared-skills membership with that installation id.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  method_not_allowed: { class: 'caller', summary: "The HTTP method is not allowed on this endpoint." },
  migration_lease_lost: { class: 'server', summary: "This apply-migrations run's own migration lease no longer matched its fence, so it stopped before the next migration.",
    why: 'The lease row still names this process (pid and host), but the fenced refresh matched no row: the direct and main database connections may reach different databases, or the row was rewritten. The details say whether the acquisition token and acquisition time still match (never the token itself). Run `gbrain doctor --json` and report it (#6028).' },
  migration_failed: { class: 'server', summary: "A migration orchestrator failed, so the migration chain stopped; finished migrations stay recorded.",
    reasons: ['orchestrator_failed', 'orchestrator_threw', 'ledger_write_failed', 'preview_failed', 'schema_failed'] },
  migrations_pending: { class: 'caller', summary: "Schema migrations are behind (or could not be confirmed at head), so the command did not report success.",
    why: 'apply-migrations reasons: not_applied: the run had no --yes (or --non-interactive), so it did not apply the schema migrations; the fix applies them with --yes. still_behind: an authorized run tried them and they did not apply; another --yes repeats the failure, so run `gbrain doctor --json` and report. schema_unreadable: the schema version could not be read back after the orchestrators ran, so the run cannot confirm it reached head; report it. Each failure names the schema migrations still pending.',
    suggestion: 'not_applied: apply them with `gbrain apply-migrations --yes`. still_behind or schema_unreadable: run `gbrain doctor --json` and report it to the user; another --yes repeats the failure.',
    reasons: ['not_applied', 'still_behind', 'schema_unreadable'] },
  migrations_running: { class: 'retryable', summary: "Another apply-migrations run holds the migration orchestration lock.", exit: 75 },
  missing_source_scope: { class: 'server', summary: "A remote tool call reached dispatch without a resolved source scope; the shared default source is refused." },
  missing_source_value: { class: 'caller', summary: "A source flag was given without a value." },
  models_strict_violation: { class: 'caller', summary: "A configured model is not allowed under models strict mode." },
  no_pricing: { class: 'unavailable', summary: "gbrain has no price for the model, so a user-set cost cap cannot be enforced." },
  no_refresh_token: { class: 'caller', summary: "Google connect credential error: no refresh token.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  no_routing_eval: { class: 'caller', summary: "The skill has no routing-eval rows to bootstrap a benchmark from." },
  no_skill_md: { class: 'caller', summary: "The skill directory has no SKILL.md." },
  no_worker: { class: 'caller', summary: "No worker is running for this queue, so a queued job would wait until something runs it.", why: "PGLite brains have no background worker (the database is single-writer), and a Postgres queue needs a running `gbrain jobs work` or supervisor. Queuing without one leaves the job waiting with no error." },
  no_worker_surface: { class: 'caller', summary: "No worker surface." },
  not_a_git_repo: { class: 'caller', summary: "The source path must contain committed Git content." },
  not_connected: { class: 'caller', summary: "Google connect credential error: not connected.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  no_brain: { class: 'caller', summary: "No brain is configured on this machine.", suggestion: 'Run `gbrain init --pglite --no-embedding` to create a local keyless brain (or `gbrain init --help` for hosted and Postgres options).' },
  not_found: { class: 'caller', summary: "The requested resource does not exist or is not visible to this caller.", legacy_error: 'invalid_params' },
  overlapping_path: { class: 'caller', summary: "Sources cannot claim overlapping canonical directories." },
  owner_unavailable: { class: 'retryable', summary: "The source's canonical owner cannot run this write or maintenance step right now; `reason` says which condition.",
    why: "A managed source publishes only through the host that owns its checkout. `host_mismatch`: another host id owns it (two GBRAIN_HOME identity files on one machine look the same; both ids are printed, and a retry on this host cannot help). `transfer_in_progress`: the worktree is draining for a writer transfer; `clone_in_progress`: a topology clone is recovering it; both clear by themselves. `binding_missing`, `incarnation_changed`, `local_path_missing` and `coordination_path_missing` name an incomplete or outdated registration. `not_sent` / `outcome_unknown`: the local owner's IPC lane did not take the write, or lost its acknowledgment.",
    reasons: ['host_mismatch', 'transfer_in_progress', 'clone_in_progress', 'binding_missing', 'incarnation_changed', 'coordination_path_missing', 'local_path_missing', 'not_sent', 'outcome_unknown'],
    docs: 'docs/guides/troubleshooting.md#owner-unavailable',
    suggestion: 'Read gbrain sources writer status --source <id> --json on the brain host. A transfer or clone in progress: wait and retry. host_mismatch: run the step on the owner host, or give the worker and the shell one GBRAIN_HOME; never copy or regenerate host.json. Nothing claims or transfers ownership to run maintenance.' },
  page_identity_changed: { class: 'caller', summary: "The page was deleted or replaced while the operation ran.", fix: { argv: ['gbrain', 'get', '--source', '{source_id}', '--', '{slug}'], mcp: { tool: 'get_page', arguments: { slug: '{slug}', source_id: '{source_id}' } }, consent: [], actor: 'agent', why: "Shows which page holds the slug now and its revision; a new attempt needs a new request_id.", requires_exclusive: false } },
  page_projection_conflict: { class: 'retryable', summary: "Another worker installed a newer search projection of the page while this command prepared its own.", why: "The projection guard keeps the newer installation instead of overwriting it; the canonical page revision did not change.", docs: 'docs/guides/repair.md#page-projection-conflict', suggestion: "Re-run the same command; it re-reads the current projection. If it conflicts again, wait for the other worker to finish." },
  page_not_found: { class: 'caller', summary: "No page with that slug exists in the selected source.", legacy_error: 'page_identity_changed', fix: { argv: ['gbrain', 'get', '--source', '{source_id}', '--', '{slug}'], mcp: { tool: 'get_page', arguments: { slug: '{slug}', source_id: '{source_id}' } }, consent: [], actor: 'agent', why: "Confirms whether the page exists in this source before anything is recreated.", requires_exclusive: false } },
  parse_error: { class: 'caller', summary: "The request body is not valid JSON." },
  parser_regression: { class: 'server', summary: "A file whose exact bytes imported before is now refused by gbrain's frontmatter reader.", why: "The same bytes imported under an earlier gbrain version, so only gbrain changed; with `sync.parser_regression=hold` such a file is held and the rest of the sync continues.", suggestion: 'Report it as a gbrain bug with the gbrain version, the file and the code; upgrade or pin the last good version, then sync again with --retry-failed.' },
  pasted_wrong_url: { class: 'caller', summary: "Google connect credential error: pasted wrong url.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  payload_too_large: { class: 'caller', summary: "The payload exceeds the configured size cap." },
  pattern_claims_pending: { class: 'retryable', summary: "An existing pattern page is waiting on the rewrite that de-duplicates its claim sources, so no patterns child was submitted this run.", why: "The patterns child reads existing pattern pages; until their claim records reference one shared reflection list, the pages can overflow the model's window and the run pays for nothing.", fix: { argv: ['gbrain', 'write-requests', '--source', '{source_id}'], consent: [], actor: 'agent', why: 'Lists the write receipts of the source, newest first, so the held rewrites show, read-only.', requires_exclusive: false } },
  pending_writes: { class: 'retryable', summary: "A pending source write prevents verified completion." },
  permission_denied: { class: 'host_only', summary: "This caller is not authorized for the operation." },
  persistence_write_stall: { class: 'host_only', summary: "A managed write request has held its claim longer than persistence.max_claim_ms, so later writes on its root wait behind it.", why: "The owner renews a claim for as long as its work is unsettled, so a preparation or publication that hangs never lets the lease lapse; doctor names the stuck phase, the root, the claim's age and whether the same request resumes on its own.", docs: 'docs/guides/troubleshooting.md#persistence-write-stall', suggestion: 'Inspect the request with the command in fix, then restart the gbrain serve that owns the root; attach that status output when reporting the hang.', fix: { argv: ['gbrain', 'sources', 'writer', 'status', '--source', '{source_id}', '--json'], consent: [], actor: 'agent', why: "Shows the owner, the stuck request's claim phase and the writes waiting behind it, read-only.", requires_exclusive: false } },
  pglite_busy: { class: 'retryable', summary: "Another gbrain process holds this PGLite brain's single-writer lock.", reasons: ['timeout', 'live_serve'], suggestion: 'Wait for the current command or server to close, then retry. Do not remove a live lock.' },
  pglite_vector_index_too_large: { class: 'unavailable', summary: "A PGLite vector (HNSW) index build was refused before it started because its in-memory graph would not fit PGLite's WebAssembly heap.", why: "pglite.wasm caps memory at 2 GiB and pgvector keeps the whole HNSW graph in memory while it builds; a build past the budget used to run out of memory or fall back to hours of on-disk inserts. Vector search keeps working with exact scans.", docs: 'docs/ENGINES.md#pglite-vector-index-ceiling', suggestion: 'Preview a move to Postgres (read-only): gbrain migrate --to postgres --plan --json', fix: { argv: ['gbrain', 'migrate', '--to', 'postgres', '--plan', '--json'], consent: [], actor: 'agent', why: 'Read-only: lists what moves to Postgres, the blockers and the exact run command.', requires_exclusive: false } },
  plan_output_failed: { class: 'server', summary: "Writing the plan output failed." },
  plan_stale: { class: 'caller', summary: "The saved plan has no valid repository identity." },
  port_in_use: { class: 'retryable', summary: "Google connect credential error: port in use.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  preparation_stalled: { class: 'server', retryable: false, actor: 'host_admin',
    summary: "A managed write's preparation was cut off at its deadline persistence.max_preparation_attempts times (default 2), so the owner finished it failed instead of claiming it again.",
    why: "One request whose preparation never finished used to hold its root for as long as its owner renewed the claim; now each attempt has a budget, a cut-off attempt is counted (a kill mid-preparation included), and at the limit the request is terminal so the rest of the root keeps moving. A sync holds that file with the same code; the receipt names the last recorded step and what it was waiting on.",
    docs: 'docs/guides/write-refusals.md#preparation_stalled',
    suggestion: 'Inspect the owner with gbrain sources writer status --source <id> --json (the step and its wait cause), fix or report the cause, then gbrain sources retry-held <id> and the same gbrain sync with the same options; a foreground write needs a new request_id.',
    fix: { argv: ['gbrain', 'sources', 'status', '{source_id}', '--json'], consent: [], actor: 'host_admin', why: 'Read-only: lists the held files of the source with their repair route.', requires_exclusive: false } },
  preview_changed: { class: 'caller', summary: "The state changed since the approved preview." },
  profile_incompatible: { class: 'caller', summary: "The stored profile is incompatible with this operation." },
  projection_owner_resident: { class: 'host_only', summary: "A resident owner holds the projection." },
  keyword_candidates_incomplete: { class: 'unavailable', summary: "Hybrid search's CJK keyword arm hit its deadline or candidate cap on a large corpus, so some keyword matches can be missing.", why: 'The CJK fallback is an unindexed LIKE scan; the arm is bounded so a large brain cannot stall every hybrid search. An incomplete keyword search is not evidence of absence.', docs: 'docs/guides/multi-language-fts.md#cjk-keyword-budget', suggestion: 'Narrow the search with --source-id (MCP source_id), or ask the user to raise search.cjk_keyword_deadline_ms.', fix: { argv: ['gbrain', 'config', 'get', 'search.cjk_keyword_deadline_ms'], consent: [], actor: 'agent', why: 'Shows the deadline in effect (unset means 3000 ms); read-only.', requires_exclusive: false } },
  projection_pending: { class: 'retryable', summary: "The current text projection is not ready." },
  provenance_required: { class: 'caller', summary: "provenance is required and must be non-empty." },
  publication_pending: { class: 'retryable', summary: "The catalog adoption is accepted but not fully committed." },
  purge_blocked_pending_recovery: { class: 'retryable', summary: "A purge was refused because a pending, running or recovering write still needs the content it would remove; nothing was purged.", why: "Purge redacts stored write intents and rewrites pages; doing that under an unfinished publication or recovery would lose or resurrect content.", suggestion: 'Wait for the named write to finish or recover (gbrain write-request <id>), then retry the purge with the same request id.', docs: 'docs/guides/memory-boundaries.md#purge' },
  purged_content: { class: 'caller', summary: "The content matches a purged fact, take or page in this source, so it was not saved.", why: "A purge leaves a text-free tombstone (the claim fingerprint or the page content hash) so stale files, re-syncs, reverts and re-extraction cannot bring purged content back.", suggestion: 'Do not retry the same content. Write it in new words if it is still true, or ask the user to clear the tombstone on the brain host (gbrain pages purges list, then gbrain pages unpurge <slug> for a page).', docs: 'docs/guides/memory-boundaries.md#purge' },
  queue_capacity: { class: 'retryable', summary: "The bounded queue is full; existing requests keep their place." },
  rate_limited: { class: 'retryable', summary: "The request was rate-limited; retry after the stated delay." },
  receipt_conflict: { class: 'retryable', summary: "The ingestion receipt changed since it was read.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  receipt_fence_changed: { class: 'caller', summary: "The managed owner, topology or source binding changed while the ingestion ran.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  receipt_fence_required: { class: 'host_only', summary: "Ingestion into a managed or bound source needs the worktree owner's fence.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  receipt_identity_mismatch: { class: 'caller', summary: "The receipt ID is already bound to different approved ingestion metadata.", docs: 'docs/guides/company-brain-ingestion.md#agent-and-ci-use' },
  recovery_required: { class: 'host_only', summary: "An earlier write left state that must be inspected and recovered before new writes." },
  redirect_uri_mismatch: { class: 'caller', summary: "Google connect credential error: redirect uri mismatch.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  ref_not_in_answer: { class: 'caller', summary: "The rated page is not one of the pages the answer used.", docs: 'docs/guides/retrieval-feedback.md#ref_not_in_answer' },
  refresh_dirty: { class: 'caller', summary: "The worktree has uncommitted changes." },
  refresh_diverged: { class: 'caller', summary: "The worktree diverged from its upstream; a fast-forward is impossible." },
  refresh_drain_timeout: { class: 'retryable', summary: "In-flight work did not drain before the refresh deadline." },
  refresh_no_upstream: { class: 'caller', summary: "The worktree has no upstream to refresh from." },
  refresh_not_managed: { class: 'host_only', summary: "The source is not managed, so it cannot be refreshed." },
  refresh_not_owner: { class: 'host_only', summary: "This process does not own the worktree it would refresh." },
  refresh_source_changed: { class: 'caller', summary: "The source changed during the refresh." },
  relay_disabled: { class: 'caller', summary: "Google connect credential error: relay disabled.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  relay_session_expired: { class: 'caller', summary: "Google connect credential error: relay session expired.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  relay_unreachable: { class: 'retryable', summary: "Google connect credential error: relay unreachable.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  rename_held: { class: 'caller', summary: "A renamed file is held because the page it was renamed from changed after the rename was recorded.", reasons: ['rename_source_changed'], why: "Moving the page now could carry the newer edit to the wrong file, so the rename waits for an explicit re-bind.", suggestion: 'Preview the frontmatter repair with --include-ambiguous to re-bind the rename to the current page, and approve it.' },
  request_already_submitted: { class: 'caller', summary: "This optimizer publication request has already been submitted." },
  request_too_large: { class: 'caller', summary: "The request exceeds a configured capacity; narrow it." },
  requirements_changed: { class: 'caller', summary: "The runtime requirements exceed the owner-approved publication policy." },
  requires_local_engine: { class: 'host_only', summary: "This command needs the brain's local database, and this install is a thin client of a remote brain." },
  response_too_large: { class: 'caller', summary: "Persistence response exceeds the local transport limit." },
  resume_spec_mismatch: { class: 'caller', summary: "Resume spec mismatch." },
  revision_conflict: { class: 'caller', summary: "The target changed since it was read; the expected revision no longer matches.", fix: { argv: ['gbrain', 'get', '--source', '{source_id}', '--', '{slug}'], mcp: { tool: 'get_page', arguments: { slug: '{slug}', source_id: '{source_id}' } }, consent: [], actor: 'agent', why: "Reads the current page and revision; resubmit against that revision with a new request_id.", requires_exclusive: false } },
  revision_required: { class: 'caller', summary: "Review the current policy and supply its expected_policy_epoch before changing disclosure." },
  revision_unavailable: { class: 'unavailable', summary: "The exact authorized revision is unavailable." },
  scope_denied: { class: 'host_only', summary: "The connection lacks the scope this memory verb requires." },
  scope_missing: { class: 'caller', summary: "Google connect credential error: scope missing.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  serve_port_in_use: { class: 'unavailable', summary: "gbrain serve --http could not listen: another process already holds that host and port.", suggestion: 'Stop the process on that port, or start the server with another --port and point the harnesses at it.' },
  serve_status_only: { class: 'unavailable', summary: "gbrain serve is in status-only mode: its brain is locked by another server, missing, damaged, or its config is unreadable.", reasons: ['lock_held', 'no_brain', 'config_unreadable', 'missing_brain', 'brain_unopenable', 'repair_failed', 'unavailable'], suggestion: 'Call gbrain_status for the cause, the fix and what to tell the user.' },
  shared_skills_unavailable: { class: 'unavailable', summary: "The shared-skills operation was refused." },
  shared_skills_unsupported: { class: 'unavailable', summary: "The server does not expose the shared-skills protocol." },
  skill_asset_not_found: { class: 'caller', summary: "The requested file is not in the approved revision manifest." },
  skill_bundle_required: { class: 'caller', summary: "Import cannot publish skill paths." },
  skill_candidate_invalid: { class: 'caller', summary: "The optimized candidate changed protected frontmatter or has an empty/invalid body." },
  skill_not_found: { class: 'caller', summary: "No authorized published skill matches this key." },
  skill_retention_capacity: { class: 'caller', summary: "Retained skill revisions exceed this source storage budget." },
  skill_unavailable: { class: 'caller', summary: "The qualified shared skill is not in this installation's current authorized view.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  source_binding_required: { class: 'caller', summary: "A write needs an explicit source binding on this MCP server (--source-guard)." },
  source_changed: { class: 'caller', summary: "The source changed during the operation; nothing was committed." },
  source_id_taken: { class: 'caller', summary: "This source already exists and does not match this exact admitted request." },
  source_not_ready: { class: 'caller', summary: "A committed source and approved schema are required." },
  source_profile_no_backfill: { class: 'unavailable', summary: "This source profile disables automatic embedding backfill." },
  source_referenced: { class: 'caller', summary: "OAuth clients still reference this source." },
  source_root_conflict: { class: 'caller', summary: "Multiple active sources alias this canonical skill root; resolve ownership before publishing." },
  source_writeback_required: { class: 'host_only', summary: "Canonical preparation requires a source-content correction; this profile never writes repository files." },
  split_bad_ratio: { class: 'caller', summary: "Split bad ratio." },
  split_unparseable: { class: 'caller', summary: "Split unparseable." },
  stale_unavailable: { class: 'unavailable', summary: "No complete, current authorized shared-skills view is available; cached shared skills stay unused.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  state_mismatch: { class: 'caller', summary: "Google connect credential error: state mismatch.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  storage_error: { class: 'server', summary: "Reading or writing durable storage failed." },
  sync_not_applicable: { class: 'caller', summary: "Sync does not apply to this source: its directory is not a Git checkout.", why: "Sync imports changes between Git commits. A gbrain-owned content directory (created by init) holds files gbrain manages itself and is not a Git repository, so there is nothing to sync; gbrain never initializes Git on its own.", reasons: ['content_directory'] },
  sync_in_progress: { class: 'retryable', summary: "A sync is running on this source, or a write in flight or the sync's frozen manifest still names the file a repair would write.",
    why: "A repair that changed a file the running sync admits later would make that entry refuse on its raw hash, and a file a write in flight names would be written twice; so the one candidate waits while the rest of the source is repaired. `candidate_in_flight`: the file is named; `busy_set_unreadable`: the busy set could not be read, so every candidate waited.",
    reasons: ['candidate_in_flight', 'busy_set_unreadable'],
    suggestion: 'Nothing to do for the repair: the next run reads the file again. To finish the sync now: gbrain sync --source <id> --no-pull.' },
  sync_parser_regression: { class: 'server', summary: "Sync stopped because gbrain would hold a file whose exact bytes imported before; this is a gbrain bug.", why: "The upgrade invariant says a newer reader never refuses bytes an older one imported, so the run stops without advancing rather than hide a regression.", suggestion: 'Report it with the gbrain version, the file and the code; upgrade or pin the last good version, then run gbrain sync --source <id> --no-pull --retry-failed.' },
  tail_exposure_approval: { class: 'caller', summary: "A fence on a world-visible page has no end marker and prose follows its table; closing it after the last row is safe for the table but makes those lines visible to remote readers, so the content-repair lane previews the close and waits for a hash-bound approval instead of applying it unattended.", why: "Everything after an unpaired begin marker is hidden by the privacy boundary. The repair model read the tail as prose (not rows), so the only judgment left is whether those exact lines may become visible, and that is the user's: the preview prints them and the hash binds them. On a private page nothing new is disclosed and the lane closes the fence by itself.", actor: 'user', docs: 'docs/guides/write-refusals.md#tail_exposure_approval', suggestion: 'Show the user the preview\'s exposed lines (gbrain repair content --source <id> --only <path>, read-only), then run the printed gbrain repair content --source <id> --only <path> --apply --expect <hash> only after they agree; a changed tail invalidates the hash. By hand: add the end marker directly after the last table row and move the trailing text where it belongs, commit, then gbrain sync --source <id> --no-pull.' },
  take_row_collision: { class: 'caller', summary: "A takes fence row number is already used by a different take that is not in this page's canonical fence." },
  target_escape: { class: 'caller', summary: "The skill target must remain within its selected root." },
  timeline_comment_markup: { class: 'caller', summary: "A stored timeline row carries HTML comment markup, so gbrain keeps it database-side and never writes it back into the page; clean it with gbrain repair timeline-comments.", docs: 'docs/guides/repair.md#timeline-comments' },
  timeline_rows_would_be_removed: { class: 'caller', summary: "A remote put_page or put_pages entry has no Timeline section and would delete the page's dated entries; resend it with the section or with drop_timeline: true.", docs: 'docs/guides/write-refusals.md#timeline_rows_would_be_removed' },
  timeout: { class: 'retryable', summary: "The operation did not finish within its time bound.", exit: 124 },
  topology_change_required: { class: 'host_only', summary: "Adding this source would replace or overlap another owner root." },
  transcript_secret_exposure: { class: 'unavailable', summary: "Imported conversation pages may still carry a typed credential from before the labeled-credential detector, or the last audit found some; pages are never rewritten automatically.", why: 'Re-ingest skips unchanged sessions, so pages imported before the detector keep any password typed in prose until someone reviews them.', docs: 'docs/guides/data-ingestion.md#credential-redaction', suggestion: 'Run the read-only audit to list affected slugs (never values), then review, edit or (after asking the user) remove each page, and ask the user to rotate any real credential.', fix: { argv: ['gbrain', 'transcripts', 'audit-secrets', '--json'], consent: [], actor: 'agent', why: 'Lists conversation pages that still carry a credential with hit counts per pattern; changes no page.', requires_exclusive: false, verify: { argv: ['gbrain', 'doctor', '--only', 'transcript_secret_exposure', '--json'] } } },
  triage_unreliable_backoff: { class: 'retryable', summary: "Dream triage did not re-judge a transcript because its last judge verdict was truncated, refused or unparseable and its backoff has not ended.", why: 'An unreliable verdict is never cached, so without a backoff the same input was paid for every cycle; it waits 24h, doubling per repeat up to 7 days, and a content or triage-model change re-judges at once.', docs: 'docs/guides/error-codes.md#triage_unreliable_backoff', suggestion: 'Leave it (it is retried after the backoff), or ask the user before `gbrain dream retriage --force`, which re-judges every transcript now and pays per file.', fix: { argv: ['gbrain', 'dream', 'retriage', '--dry-run', '--json'], consent: [], actor: 'agent', why: 'Lists the transcripts that still need a verdict without any judge call, read-only.', requires_exclusive: false } },
  trust_raise_refused: { class: 'consent', exit: 3, actor: 'user', summary: "A write tried to raise the trust tier of a fact, take, page or timeline entry without the owner's confirmation, so nothing was changed.", why: "Only the owner can make memory more trusted: confirming on an interactive terminal, or through a connection that holds the memory_confirm scope. The database refuses any other raise so a bug or an agent write cannot promote its own content.", docs: 'docs/guides/error-codes.md#trust_raise_refused', suggestion: 'Do not retry. Ask the user to confirm the row themselves on the brain host (gbrain trust confirm <ref>), or leave its tier as it is.' },
  two_consumers_on_host: { class: 'host_only', summary: "Two resident gbrain processes on this host (`serve`, `sync`, `jobs`, `autopilot` or `mcp`) have each run a full persistence consumer for longer than 30 s, so both claim writes on the same roots.", why: "One full consumer per host is a preference, not a fenced role: a `serve` always starts full, every other resident kind defers to the first live full consumer it finds in `persistence_consumers`, and two processes that start within one renewal of each other, or a CLI that took its consumer before the `serve` started, both stay full until one exits. Every observed `preparing` wedge had two consumers alive on the host. Short-lived commands (`put`, `import`, `dream`, `cli`) and rows younger than 30 s are listed, never warned.", docs: 'docs/guides/troubleshooting.md#two-consumers-on-host', suggestion: 'Let the shorter-lived of the two finish (a sync CLI run ends on its own) or restart it so it defers; with persistence.single_consumer off, this is the configured behavior.', fix: { argv: ['gbrain', 'sources', 'writer', 'status', '--json'], consent: [], actor: 'agent', why: 'Read-only: lists every consumer alive on this host (pid, kind, mode, started_at, pool) so you can see which one to let finish.', requires_exclusive: false, verify: { argv: ['gbrain', 'doctor', '--only', 'two_consumers_on_host', '--json'] } } },
  trusted_local_only: { class: 'host_only', summary: 'The operation runs only from the trusted local CLI on the brain host; no MCP connection can call it.', legacy_error: 'permission_denied', suggestion: 'Ask the user to run the named gbrain command on the brain host.' },
  unavailable: { class: 'unavailable', summary: "A required dependency or capability cannot serve this request." },
  unclosed_ambiguous_tail: { class: 'caller', summary: "A fence has no end marker and text follows its table, and the repair model read that tail as table rows written without pipes or could not tell, so gbrain will not choose where the fence ends; nothing was written.", why: "Closing after the wrong row would hide rows behind the privacy boundary or expose text; a deterministic rule cannot place the end marker and the model declined to, so a person decides. The attempt memo keeps the same bytes from costing a second model call.", actor: 'user', docs: 'docs/guides/write-refusals.md#unclosed_ambiguous_tail', suggestion: 'Read the page (gbrain get --source <id> -- <slug>), add the end marker after the last real row of the named fence (moving any rows the tail holds into the table), commit, then gbrain sync --source <id> --no-pull. The preview (gbrain repair fences --source <id> --only <path>, read-only) names the fence, section and last row.', fix: { argv: ['gbrain', 'repair', 'fences', '--source', '{source_id}'], consent: [], actor: 'agent', why: 'Read-only: names each held fence with its section and last parsed row so the person knows where the end marker belongs; writes nothing and calls no model.', requires_exclusive: false, verify: { argv: ['gbrain', 'sources', 'status', '{source_id}', '--json'] } } },
  unexpected_file_bytes: { class: 'server', summary: "A canonical skill file mode changed outside publication." },
  unexpected_staging_bytes: { class: 'server', summary: "Recovery staging has unexpected bytes or identity; the root and its recovery capacity remain reserved." },
  unknown: { class: 'server', summary: "An unclassified failure (legacy StructuredError fallback code)." },
  unknown_command: { class: 'caller', summary: "The CLI has no command by that name.", suggestion: 'Run `gbrain --help` for the command list.', exit: 2 },
  unknown_flag: { class: 'caller', summary: "The command does not accept one of the flags passed.", exit: 2 },
  unknown_method: { class: 'caller', summary: "The JSON-RPC method is not supported." },
  unknown_source: { class: 'caller', summary: "The named source is not registered or is archived." },
  unknown_tool: { class: 'caller', summary: "The named tool does not exist or is not callable on this connection.", legacy_error: 'unknown_operation' },
  unknown_transport: { class: 'unavailable', summary: "The caller's transport could not be identified." },
  unmanaged_path: { class: 'caller', summary: "Reclone only replaces a checkout created and managed by GBrain." },
  unsupported_export_data: { class: 'unavailable', summary: "The source contains data this export path cannot carry." },
  unsupported_mutation_protocol: { class: 'unavailable', summary: "Prepared mutation does not match its accepted target." },
  upstream: { class: 'retryable', summary: "Google connect credential error: upstream.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  verification_failed: { class: 'server', summary: "Source content or relationships changed during verification." },
  withdrawal_capacity: { class: 'caller', summary: "Withdrawal capacity." },
  withdrawal_provenance: { class: 'server', summary: "The withdrawal target manifest is invalid." },
  write_claim_lost: { class: 'retryable', summary: "Execution claim changed before publication." },
  write_gate_rejected: { class: 'caller', summary: "The write gate refused external instruction-like content because the operator set `write_gate.external_mode` to `reject`.", why: "Text from an untrusted source that reads like an instruction to an agent (an override, a standing rule, an exfiltration or credential request) is refused instead of held under that setting, so nothing was written. The same content refuses on every retry.", reasons: ['override', 'standing_instruction', 'exfiltration', 'credential', 'detector_error'], suggestion: 'Tell the user the content was refused; whether to accept it or switch `write_gate.external_mode` back to `quarantine` is their decision.' },
  write_held: { class: 'consent', summary: "The write gate held this content for the owner's review instead of saving it as memory.", why: "Content from an untrusted source read like an instruction to an agent, so it was quarantined in the write-gate holding table. It is not searchable or recalled until the owner releases it; retrying the same write only re-opens the same hold.", reasons: ['override', 'standing_instruction', 'exfiltration', 'credential', 'detector_error'], actor: 'user', exit: 3, suggestion: 'Do not retry. Tell the user what was held and give them the release command from the fix; releasing is their decision.' },
  write_outcome_unknown: { class: 'retryable', retryable: false, actor: 'agent',
    summary: "The database connection dropped while a write was being admitted, and it kept dropping through the re-reads, so whether the write was accepted is unknown.",
    why: "A session that closes under an admission (a pooler reap, a failover, pg_terminate_backend) leaves the transaction either committed or rolled back with no way to tell from the lost socket. gbrain re-runs the attempt, which starts by reading the retained request_id, so a single drop resolves by itself; this code means the database stayed unreachable through those re-reads. Before #6355 the raw socket error reached the caller, and a receipt oracle took it for a refusal while the write committed.",
    docs: 'docs/guides/write-refusals.md#write_outcome_unknown',
    suggestion: 'Read the request first (the fix names it): a committed or pending row means the write was accepted, replay the same request_id to wait for it; no row means it was not, submit it again with the same request_id. Never resubmit under a new request_id without that read.' },
  write_pending: { class: 'retryable', summary: "The write was accepted and is still pending; it may commit later.", exit: 10 },
  worktree_dirty: { class: 'caller', retryable: false, actor: 'agent',
    summary: "A managed sync held a file whose uncommitted working-tree bytes match neither the pinned commit nor the current page; the rest of the source synced and the local edit was not overwritten.",
    why: "On a live checkout an agent may be mid-edit on a file the catch-up reaches. The bytes are not committed at HEAD, so sync cannot tell a deliberate local change from a stray one, and importing the pinned version would discard the edit; before #6340 this refusal stopped the whole run.",
    docs: 'docs/guides/write-refusals.md#worktree_dirty',
    suggestion: 'Commit the file (or restore it), then run gbrain sync unblock --source <id> --apply (it re-screens every held file that is now committed) and the same gbrain sync; a later commit that changes the file re-screens it on its own.' },
  writer_admin_intent_required: { class: 'host_only', summary: "Topology changes require an action-specific --admin-intent and the --expected-state from a reviewed writer status." },
  writer_admin_locked: { class: 'host_only', summary: "Writer administration is locked; deactivation was not applied." },
  writer_admin_state_changed: { class: 'caller', summary: "Writer topology changed since inspection; the administrative request was not applied." },
  writer_busy: { class: 'retryable', summary: "The canonical worktree is busy with another write." },
  writer_coordinator_required: { class: 'host_only', summary: "The operation needs managed persistence (a writer coordinator) on the brain host." },
  writer_identity_invalid: { class: 'host_only', summary: "The local writer identity is invalid." },
  writer_identity_publish_failed: { class: 'host_only', summary: "The replacement writer is durable but its credential file could not be published." },
  writer_lock_unavailable: { class: 'retryable', summary: "Another activation probe is running." },
  writer_manifest_mismatch: { class: 'caller', summary: "Successor checkout differs from the recorded canonical manifest." },
  writer_manifest_rescope_required: { class: 'host_only', summary: "A writer transfer prepared by an older release covers every file of the old checkout, ignored files included, so a clean Git clone cannot match it.", why: "Transfer manifests now cover the files Git tracks, so ignored secrets such as .env files are never read, hashed or required on the successor; a manifest recorded before that change is prepared again instead of asking the user to copy ignored files.", docs: 'docs/architecture/topologies.md#transfer-manifest-scope', suggestion: 'On the owner host, run gbrain sources writer transfer prepare <source> again with its admin intent and state, then accept with the new epoch and manifest.' },
  writer_manifest_unsafe: { class: 'caller', summary: "The canonical worktree manifest cannot be recorded safely: the checkout holds a symlink or a Git submodule, a Git-scoped comparison ran on a directory Git cannot list, or Git cannot read a directory that holds .git." },
  writer_not_initialized: { class: 'host_only', summary: "Persistence identity is missing." },
  writer_not_quiesced: { class: 'host_only', summary: "Older writers or maintenance jobs are still running." },
  writer_pool_capacity: { class: 'retryable', summary: "Mirror recovery is waiting for publication capacity." },
  writer_registration_required: { class: 'host_only', summary: "Writer registration required." },
  writer_regrant_required: { class: 'host_only', summary: "This lane already has a different grant." },
  writer_transfer_conflict: { class: 'caller', summary: "Writer transfer conflict." },
  writer_transfer_required: { class: 'caller', summary: "Writer transfer required." },
  writer_upgrade_required: { class: 'host_only', summary: "Apply the canonical writer guard, outbox, and source lifecycle migrations before activation." },
  wrong_account_consented: { class: 'caller', summary: "Google connect credential error: wrong account consented.", docs: 'docs/guides/google-connect.md#troubleshooting' },
} as const satisfies Record<string, CodeEntry>;

export type RegistryCode = keyof typeof CODES;

/** One notice code (agent contract v1, A6). Lanes add producers' codes here. */
export interface NoticeEntry {
  kind: 'safety' | 'degraded' | 'coaching' | 'ask' | 'info';
  summary: string;
}

/** Notice codes. Mute (`gbrain notices mute`, `mute_notice`) accepts only coaching/info codes. */
export const NOTICE_CODES = {
  backup_coverage: { kind: 'coaching', summary: 'Some knowledge assets have no off-machine backup.' },
  empty_retrieval: { kind: 'info', summary: 'A retrieval returned no results; the notice says whether recall was degraded.' },
  first_run_decisions: { kind: 'ask', summary: 'init finished (or a stdio MCP session started on a brain with open decisions); the first-run decisions (search mode, writeback, harness wiring, skills) carry defaults the user may change. The one muteable ask.' },
  first_run_decisions_muted: { kind: 'info', summary: 'First-run decisions are still open, but the user muted them; the fix shows them again (`gbrain notices unmute first_run_decisions`).' },
  migrations_pending: { kind: 'safety', summary: 'Schema migrations are pending or failed to apply on this brain.' },
  no_worker: { kind: 'degraded', summary: 'A job was queued but no worker is running to execute it; it waits until a worker runs.' },
  unknown_param: { kind: 'info', summary: 'The call passed a parameter the tool does not declare; it was ignored.' },
  listing_truncated: { kind: 'info', summary: 'A listing returned a full page and more rows match; the fix is the next-page call.' },
  former_relationships_hidden: { kind: 'info', summary: 'A graph read returned live relationships only and left out ended ones; the fix repeats the call with status: "all" (or as_of) to see history.' },
  mention_index: { kind: 'degraded', summary: 'The entity mention index is pending, off, failed or does not cover this page type, so references listed for an entity may be incomplete.' },
  degraded_recall: { kind: 'degraded', summary: 'A retrieval stage that affects recall did not run; an empty or thin result is not proof of absence.' },
  source_binding_narrowed: { kind: 'info', summary: "A GBRAIN_SOURCE / .gbrain-source binding narrowed an unqualified read that came back empty; the fix reads another source explicitly." },
  degraded_dedup: { kind: 'info', summary: 'remember ran without an embedding provider, so only exact duplicates are detected.' },
  local_transcripts: { kind: 'info', summary: 'The brain host keeps recent session transcripts that page reads never return and this connection cannot read; the fix is the CLI read (`gbrain transcripts recent --json`).' },
  synthesis_keyless: { kind: 'info', summary: 'think returned gathered evidence without synthesis because no chat-model key is configured (by design on a keyless brain).' },
  think_not_saved: { kind: 'info', summary: 'think save/take persist only for the local CLI, so this answer was not saved.' },
  onboard_opportunities: { kind: 'coaching', summary: 'Onboarding checks found work that would improve this brain (gbrain onboard --check lists it).' },
  onboard_stale_chunks: { kind: 'coaching', summary: 'This search could not match chunks that have no embedding; the remedy is an embedding backfill (paid, ask first).' },
  onboard_link_coverage: { kind: 'coaching', summary: 'Few people/company pages have incoming links, so backlinks and graph answers are thin; the remedy is link extraction.' },
  onboard_timeline_coverage: { kind: 'coaching', summary: 'Few people/company pages have timeline entries, so dated answers are thin; the remedy is timeline extraction.' },
  onboard_no_takes: { kind: 'coaching', summary: 'The brain holds no takes, so think and recall cannot cite the user\'s own views; the remedy is recording or extracting takes.' },
  surface_env_invalid: { kind: 'info', summary: 'GBRAIN_SURFACE holds a value other than verbs, starter or full; the server ignored it and names the surface it serves.' },
  features_auto_fix: { kind: 'coaching', summary: 'gbrain features found auto-fixable gaps; the fix is the auto-fix command (it may spend on embeddings).' },
  delta_incomplete: { kind: 'degraded', summary: 'delta delivered less than is waiting and moved no cursor past it: an arm failed or the deadline fired (retry after a short wait; report after 3 consecutive wakes), or budget_tokens cannot fit one item (the fix names the budget that does).' },
  post_upgrade: { kind: 'safety', summary: 'gbrain was upgraded; behavior for scripts and agents changed — read the behavior table once.' },
  behavior_changes: { kind: 'safety', summary: 'One-time disclosure of behavior an upgrade turned on (a live chat_fallback_chain, managed-brain lint repairs, smaller transcript parts, a mention-linker rescan); everything stays on, and the fix is optional.' },
  chat_fallback_hop: { kind: 'safety', summary: 'chat_fallback_chain sent a request to another model for the first time in this process; names the failed and the next model.' },
  facts_drain_first_run: { kind: 'info', summary: 'The automatic facts drain is about to process its first backlog on this brain: the queued page count, the estimated spend, the caps and the opt-out.' },
  facts_drain_deferred: { kind: 'degraded', summary: 'The automatic facts drain left queued pages waiting (no key, a spend cap, an unpriced model under a user cap); the fix is the next step.' },
  relational_chain: { kind: 'degraded', summary: 'A typed relationship chain found no complete answer (start page not visible, no typed edges, an empty hop) or hit a cap; the notice names the hop and the next call.' },
  held_files: { kind: 'degraded', summary: 'Sync holds files in the read scope it cannot import: held new files are missing and pages whose newer file is held are stale; the fix is the repair preview on the brain host.' },
  recovered_frontmatter: { kind: 'coaching', summary: 'Files imported only after quoting unquoted frontmatter values; the generator writing them should quote values (the fix is the repair preview).' },
  page_quarantined: { kind: 'safety', summary: 'The page was quarantined by the content-quality gate (hidden from search; its facts and takes are not extracted). A read says to treat its text as untrusted scraped content and, for an untrusted reader, that its body was withheld (an admin-scoped caller may pass include_quarantined: true); a write says the page was hidden and that the operator clears a false positive with gbrain quarantine clear <slug> --force.' },
  fence_normalized: { kind: 'coaching', summary: 'A write\'s facts or takes fence was rewritten losslessly (rows and classes named, never values): the stored page differs from what was sent, so re-read it with get_page before editing; remember and takes_add write rows that never need it.' },
} as const satisfies Record<string, NoticeEntry>;
