#!/usr/bin/env bun
/**
 * Operation manifest generator: every operation's data (name, description,
 * params, scope, flags, annotations, cliHints) without its handler.
 *
 * Output: src/core/operation-manifest.generated.ts (committed). `gbrain serve`
 * builds initialize and tools/list from it and the CLI dispatcher resolves
 * commands from it, so neither loads the ~760-module handler graph behind
 * src/core/operations.ts until a call actually runs. Freshness is pinned by
 * test/operation-manifest.test.ts; tools/list byte-identity against the eager
 * registry by test/mcp-tool-list-snapshot.test.ts.
 *
 * Regenerate: bun run build:operation-manifest
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { operations } from '../src/core/operations.ts';

export const OPERATION_MANIFEST_PATH = join(import.meta.dir, '..', 'src', 'core', 'operation-manifest.generated.ts');

export function renderOperationManifest(): string {
  const meta = operations.map(({ handler: _handler, ...rest }) => rest);
  return [
    '// AUTO-GENERATED by scripts/build-operation-manifest.ts — do not edit by hand.',
    '// Regenerate: bun run build:operation-manifest',
    '// Freshness pinned by test/operation-manifest.test.ts.',
    '//',
    '// Merge conflict here? Take either side wholesale, then re-run the command above.',
    '//',
    '// Every operation in src/core/operations.ts minus its handler, in registry',
    '// order. Read by the MCP stdio server (initialize, tools/list) and the CLI',
    '// dispatcher so they stay off the handler module graph until a call runs.',
    "import type { OperationMeta } from './ops/contract.ts';",
    '',
    `export const OPERATION_MANIFEST: OperationMeta[] = ${JSON.stringify(meta, null, 2)};`,
    '',
  ].join('\n');
}

if (import.meta.main) {
  const out = renderOperationManifest();
  writeFileSync(OPERATION_MANIFEST_PATH, out, 'utf-8');
  console.log(`Wrote ${OPERATION_MANIFEST_PATH} (${operations.length} operations, ${out.length} bytes).`);
}
